# Setup
title:               IX Lab
tagline:             Interaction+X Lab
description:         Interaction+X Lab
url:                 'https://ixlab.cau.ac.kr'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Eunji Park
  url:               'https://ixlab.cau.ac.kr'
  email:             eunjipark@cau.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             17 Oct, 2024
google_analytics_id: #UA-XXXX-Y
